import json
import pandas as pd

# this scripts takes the json file generated by running:
# curl "http://finaledb.research.cchmc.org/api/v1/seqrun?instrument=HiSeq%202000&limit=1000" > data/candidates.json
# and filters only samples from a specific author from input
# TODO previous curl command only fetches samples using hiseq2000

# urls in the last column are to be appended to 'https://finaledb.research.cchmc.org/'
with open("./data/candidates.json") as file:
    data = json.load(file)

rows = []
author = input("Enter author name:")

for r in data["results"]:
    authors = r.get("publication", {}).get("author", [])
    if not any(author in a for a in authors):
        continue

    if r["seqConfig"]["readlen"] != 100:
        continue

    if r["seqConfig"]["instrument"] != "HiSeq 2000":
        continue

    rows.append({
        "seqrun_id": r["id"],
        "sample_name": r.get("sample", {}).get("name"),
        "disease": r.get("sample", {}).get("disease"),
        "tissue": r.get("sample", {}).get("tissue"),
        "read_length": r["seqConfig"]["readlen"],
        "instrument": r["seqConfig"]["instrument"],
        "frag_tsv_hg19": next(
            x["key"] for x in r["analysis"]["hg19"]
            if x["desc"] == "fragment"
        )
    })

df = pd.DataFrame(rows)
df.to_csv("./data/manifest/cristiano_manifest.csv", index=False)

print("number of cristiano samples:", len(df))
