import json
import pandas as pd
import subprocess
import os

# this scripts takes the json file generated by running:
# curl "http://finaledb.research.cchmc.org/api/v1/seqrun?instrument=HiSeq%202000&limit=1000" > data/manifest/candidates.json

# fetch candidate sample from finaledb api with instrument hiseq 2000 to narrow down to samples including cristiano study
subprocess.run('curl "http://finaledb.research.cchmc.org/api/v1/seqrun?instrument=HiSeq%202000&limit=1000" > data/manifest/candidates.json', shell=True)


# urls in the last column are to be appended to 'https://finaledb.research.cchmc.org/'
with open("./data/manifest/candidates.json") as file:
    data = json.load(file)

# print list of unique author 


rows = []
author = input("Enter author name:")

# filter the fetched samples by author name (cristiano)
for r in data["results"]:
    # print keys inside sample
    print(r.get("sample", {}).keys())
    authors = r.get("publication", {}).get("author", [])
    if not any(author.lower() in a.lower() for a in authors):
        continue
    
    rows.append({
        "seqrun_id": r["id"],
        "sample_name": r.get("sample", {}).get("name"),
        "age": r.get("sample", {}).get("age"),
        "gender": r.get("sample", {}).get("gender"),
        "tissue": r.get("sample", {}).get("tissue"),
        "disease": r.get("sample", {}).get("disease"),
        "read_length": r["seqConfig"]["readlen"],
        "instrument": r["seqConfig"]["instrument"],
        "frag_num_hg19": r.get("fragNum").get("hg19"),
        # "publication": r.get("publication", {}).get("citeShort"), # skip because comma causes problems parsing
        "frag_tsv_hg19": next(
            x["key"] for x in r["analysis"]["hg19"]
            if x["desc"] == "fragment"
            ),
        "wps_bw_hg19": next(
            x["key"] for x in r["analysis"]["hg19"]
            if x["desc"] == "WPS" and x["type"] == "bigWig"
            )
    })


df = pd.DataFrame(rows)
# print(df[['wps_bw_hg19']].head())
if df.empty:
    print("No data to process.")
    exit()
# dropping rows which dont have sample name
df = df.dropna(subset=["sample_name"])

# load supplementary table from cristiano 2019 study 
# add stage information to manifest
cristiano_supplementary = pd.read_excel("./data/supplementary/2019 cristiano supplementary.xlsx", header=1)
cristiano_stages = cristiano_supplementary[["Patient", "Stage"]].drop_duplicates(subset=["Patient"])


df = df.merge(cristiano_stages, left_on="sample_name", right_on="Patient", how="inner").drop(columns=["Patient"])
df.rename(columns={"Stage": "stage"}, inplace=True)
# drop rows which have stage information other than I/II/III/IV or NA
df = df[df["stage"].isin(["I", "II", "III", "IV", float("nan")])]
print('number of rows after merging with supplementary table:', len(df))
print(df['stage'].value_counts())


if not df.empty:
    df.to_csv(f"./data/manifest/{author}_manifest.csv", index=False)
